version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2 # Use the AWS ECR orb in your config

workflows:
  build_and_push_image: 
    jobs:
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image` job
          dockerfile: Dockerfile
          profile-name: chloewakefieldd
          repo: 914890495881.dkr.ecr.eu-west-1.amazonaws.com/simpleunicornapp
          tag: latest # default - latest
