version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2 # Use the AWS ECR orb in your config
  aws-ecs: circleci/aws-ecs@1.1.0 # Use the AWS ECS orb in your config

workflows:
  build_and_push_image: 
    jobs:
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image` job
          dockerfile: Dockerfile
          profile-name: chloewakefieldd
          repo: simpleapp
          tag: latest # default - latest
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run the deployment job once the build and push image job has completed
          family: 'first-run-task-definition'
          cluster-name: 'simpleapp-cluster'
          container-image-name-updates: 'container=simpleapp-service,tag=${CIRCLE_SHA1}'
