version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  buildplease:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
workflows:
    buildplease:
      jobs:
        - buildplease